# Generated by Django 3.2.8 on 2021-10-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.CharField(default='project description', max_length=300),
        ),
    ]
