# Generated by Django 3.2.8 on 2021-10-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(default='project description', max_length=2000),
        ),
    ]
