# Generated by Django 3.2.8 on 2021-11-09 05:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
